### ISSUE TITLE
n_neurons must be int

### ISSUE THREAD

**Issue by jgosmann** [arvoelke/delay2017#5]
I'm getting this exception when building with doit:
```
TaskError - taskid:simulate_lambert
PythonAction Error
Traceback (most recent call last):
  File "/home/jgosmann/.pyenv/versions/3.6.1/lib/python3.6/site-packages/doit/action.py", line 403, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/home/jgosmann/Documents/projects/delay2017/dodo.py", line 106, in simulate_lambert
    delay, dt, t, stim, delayed, lowpass, dexp = delayed_synapse()
  File "/home/jgosmann/Documents/projects/delay2017/main.py", line 63, in delayed_synapse
    x = EnsembleArray(n_neurons / order, len(A), neuron_type=neuron_type)
  File "/home/jgosmann/.pyenv/versions/3.6.1/lib/python3.6/site-packages/nengo/networks/ensemblearray.py", line 114, in __init__
    label="%s%d" % (label_prefix, i))
  File "/home/jgosmann/.pyenv/versions/3.6.1/lib/python3.6/site-packages/nengo/base.py", line 35, in __call__
    inst.__init__(*args, **kwargs)
  File "/home/jgosmann/.pyenv/versions/3.6.1/lib/python3.6/site-packages/nengo/ensemble.py", line 148, in __init__
    self.n_neurons = n_neurons
  File "/home/jgosmann/.pyenv/versions/3.6.1/lib/python3.6/site-packages/nengo/base.py", line 106, in __setattr__
    super(NengoObject, self).__setattr__(name, val)
  File "/home/jgosmann/.pyenv/versions/3.6.1/lib/python3.6/site-packages/nengo/config.py", line 458, in __setattr__
    super(SupportDefaultsMixin, self).__setattr__(name, val)
  File "/home/jgosmann/.pyenv/versions/3.6.1/lib/python3.6/site-packages/nengo/params.py", line 112, in __set__
    self.data[instance] = self.coerce(instance, value)
  File "/home/jgosmann/.pyenv/versions/3.6.1/lib/python3.6/site-packages/nengo/params.py", line 257, in coerce
    self.check_type(instance, num, int_types + (np.integer,))
  File "/home/jgosmann/.pyenv/versions/3.6.1/lib/python3.6/site-packages/nengo/params.py", line 145, in check_type
    attr=self.name, obj=instance)
nengo.exceptions.ValidationError: Ensemble.n_neurons: Must be of type 'int or integer' (got type 'float').
```

**Comment by arvoelke** [comment]
I think you need to use Python 2.7.3 (see README.md) for requirements, as `n_neurons / order` is doing floating-point division in Python 3.

**Comment by jgosmann** [comment]
Well, I've got the PDF now, but both Python 2.7 and 3 support `//` for explicit integet division (but I suppose that might not be the only Python 3 compatibility issue)?
